# This is a basic workflow to help you get started with Actions
name: my-workflow
# Controls when the workflow will run
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_me:
    needs: next_level
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    steps:
      # Runs a single command using the runners shell
      - name: Running this job just because of someone pushed some code on practice branch
        run: echo Hello, world!
  acutal_flow:
    uses: durganath123/actions/.github/workflows/myfun.yaml@master
    with:
      username: namefromParameter
  just_checking:
    runs-on: ubuntu-latest
    steps:
      - name: this is the name of step one
        run: echo Testing the second test
      - name: okay fine
        run: echo find
  
  next_level:
   needs: [just_checking, acutal_flow]
   runs-on: ubuntu-latest
   steps: 
    - name: next level executing dependency
      run: echo This must be executed at next level
