name: Dependentjob
on: 
  workflow_run:
    workflows: ["Regular Job"]
    types: [completed]
  workflow_dispatch:
jobs:
  the_dependent_job:
    runs-on: ubuntu-latest
    steps: 
      - name: This is the step under dependent job 
        run: echo Okay i ran immediately after the regular job ran!!

