# This is a basic workflow to help you get started with Actions

name: Regular Job

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  the_normal_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hii i am at my first job!!
      - run: echo hello > world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: world.txt
